### ISSUE TITLE
PHP Notice: Function wp_enqueue_style was called incorrectly.

### ISSUE THREAD

**Issue by akerd** [MoneySpace-net/money-space-for-Woocommerce#1]
Hello,

we are using the latest version of the plugin 2.10.0 and checking the PHP error logs we see a tons of PHP Notices logged.

`[28-Mar-2024 09:40:21 UTC] PHP Notice:  Function wp_enqueue_style was called incorrectly. Scripts and styles should not be registered or enqueued until the wp_enqueue_scripts, admin_enqueue_scripts, or login_enqueue_scripts hooks. This notice was triggered by the moneyspace-block-style handle. Please see <a>Debugging in WordPress</a> for more information. (This message was added in version 3.3.0.) in /public_html/wp-includes/functions.php on line 6031`

Can you please fix this issue?

**Comment by ekapopbus** [comment]
@akerd, it seems like we are fixed, please check with latest version

**Comment by akerd** [comment]
Hi @ekapopbus thank you for the notice.

I tried to install the new version on a live store,  but the same message happen.

I also tried on a local environment store with only the standard WordPress theme enabled and just WooCommerce 9.0.1 and the lastest MoneySpace error. Same issue.

I also check the code difference between the latest and previous plugin version and I didn't find anything related to the change of moneyspace-block-style loading.

I locally tried to change the file moneyspace_payment_gateway.php from this

```
wp_register_style( 'moneyspace-block-style', plugin_dir_url( __FILE__ )."assets/js/frontend/blocks-ms-creditcard.css", array(), "1.0.0", "");
wp_enqueue_style('moneyspace-block-style');
```

to this

```
add_action(
    'wp_enqueue_scripts',
    function() {
        wp_register_style( 'moneyspace-block-style', plugin_dir_url( __FILE__ )."assets/js/frontend/blocks-ms-creditcard.css", array(), "1.0.0", "");
        wp_enqueue_style('moneyspace-block-style');
    }
);
```

and the style loading seems to work as before and no PHP notice.

Can you check? If you need I can create a Pull Request for you to test.
